# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordVerify',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegVerify',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
