# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48, unique=True)),
                ('isforum', models.BooleanField()),
                ('parentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Forumpost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Category')),
                ('parentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Forumpost')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('action', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('path', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('deadtime', models.DateTimeField()),
                ('maintitle', models.TextField()),
                ('subtitleid', models.PositiveIntegerField()),
                ('subtitle', models.TextField()),
                ('content', models.TextField()),
                ('haspicture', models.PositiveIntegerField()),
                ('popularity', models.PositiveIntegerField()),
                ('activetime', models.PositiveIntegerField()),
                ('replymethodid', models.PositiveIntegerField()),
                ('replymethod', models.CharField(max_length=48)),
                ('state', models.PositiveIntegerField()),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='public.Category')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=48, unique=True)),
                ('province', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('regstunum', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stuid', models.CharField(max_length=16, null=True)),
                ('gender', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=32, null=True)),
                ('universityid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userdetail', to='public.University')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Useremail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userlikepost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userphonenum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=32)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userqq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=32)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userwechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat', models.CharField(max_length=48)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='userlikepost',
            unique_together=set([('userid', 'postid')]),
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together=set([('postid', 'path', 'name')]),
        ),
    ]
